services:
  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "password"
        MYSQL_DATABASE: "patientdb"
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - my-db:/var/lib/mysql
volumes:
  my-db: