services:
  mysql-db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "password"
        MYSQL_DATABASE: "patientdb"
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - my-db:/var/lib/mysql

  mongo-db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  gateservice:
    build:
      context: ./gateservice
    ports:
      - "8080:8080"
    environment:
      - PATIENT_SERVICE_URL=http://patientservice:8081
    depends_on:
      - patientservice

  patientservice:
      build:
        context: ./patientservice
      ports:
        - "8081:8081"
      environment:
        - SPRING_PROFILES_ACTIVE=dev
        - MYSQL_URL=mysql-db:3306
      depends_on:
        - mysql-db

volumes:
  my-db:
  mongo-data: